# Site settings
title: jozdoo'blog
motto: 安静 做事
email: jozdoo@gmail.com
description: 杜祖洲的博客 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jozdoo.github.io" # the base hostname & protocol for your site
twitter_username: jozdoo
github_username:  jozdoo

# Build settings
markdown: kramdown
